### ISSUE TITLE
Crash: oneLineText is not a function

### ISSUE THREAD

**Issue by lex111** [gitpoint/git-point#322]
After merging #284, the following error occurs:

![screenshot_1505130524](https://user-images.githubusercontent.com/4408379/30273281-0539cd68-9701-11e7-9cf4-7c68e68a0503.png)

**Comment by machour** [comment]
same here

**Comment by arthurdenner** [comment]
That's a very strange behaviour , because the function is exported from the `utils` module.

If you try to import another function from the `text-helper` file, like abbreviateNumber, it says is `undefined` as well. I imported the whole `utils` module (`import * as utils`) and logged on the console, but only got two functions:

![utils-module](https://user-images.githubusercontent.com/13774309/30276790-530e90ca-96dc-11e7-86f8-7a7525ccdff3.PNG)

However, if I delete all the code from the `pt-br` file, the `utils` module is logged correctly and `oneLineText` is there, with all the others functions.

![utils-module-2](https://user-images.githubusercontent.com/13774309/30276908-b3007cf0-96dc-11e7-86b7-af96cf5e851c.PNG)

But if I try to log `utils.oneLineText` (or any other function except `createActionSet` and `loadingAnimation` it says is `undefined`. o.O

Any idea on why this is happening?

**Comment by housseindjirdeh** [comment]
@arthurdenner yeah it's unusual, but I think I found out why.

The only reason you're seeing results from `action-helper` and `loading-animation` when loading from `utils` is that the other files all reference `import I18n from 'locale';
` and that seems to cause them to fail. Digging in a little deeper, it looks like `locale/index.js` is importing `I18n`, updating it and just exporting it like so:

```
import I18n from 'react-native-i18n';
import { en, fr, nl, ptBr, tr } from './languages';

I18n.fallbacks = true;

I18n.translations = {
  en,
  fr,
  nl,
  tr,
  'pt-br': ptBr,
};

export default I18n; 
```

Not sure why, but using `import I18n from 'locale';` in the two helper files seem to cause them to not be exported normally. Now it seems like we're doing this in just the two files `method-helpers.js` and `text-helper.js` so we'll need to explore why exactly this is happening and how to fix it (could be a simple exports/imports thing we need to refactor)

**Comment by arthurdenner** [comment]
@housseindjirdeh. since the function is not really necessary (I just used it to avoid long vertically scrolling), we could just remove it and it will works. I've made the branch already, should I make the PR?

**Comment by housseindjirdeh** [comment]
Yeah I'm okay with that for now :) Really weird how we're only noticing it when this specific function is added however 🤔 Looks like `I18n` is causing a circular dependency issue I guess.

Happy to merge a fix for this in that just removes the function 👍

**Comment by lex111** [comment]
Closing as fixed in #325.
